databases:
  - name: Budge
    databaseName: budge
    user: budge_user

services:
  - type: web
    name: Budge_App
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budge
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
